from __future__ import annotations


OFFICIAL_STAGE2_REPO_COMMIT = "6805e2323018fbd8a85f41ca09fc33d74d5a02a5"
OFFICIAL_STAGE2_JUDGE_IMAGE_REPOSITORY = "math-distill-stage2-official-judge"
OFFICIAL_STAGE2_JUDGE_IMAGE_FIXED_TAG = "official-6805e23"
OFFICIAL_STAGE2_JUDGE_IMAGE_LATEST = f"{OFFICIAL_STAGE2_JUDGE_IMAGE_REPOSITORY}:latest"
OFFICIAL_STAGE2_JUDGE_IMAGE = (
    f"{OFFICIAL_STAGE2_JUDGE_IMAGE_REPOSITORY}:{OFFICIAL_STAGE2_JUDGE_IMAGE_FIXED_TAG}"
)
